/bin/sh: 1: /datadrive/Crontab/google_budget.sh: Permission denied
/bin/sh: 1: /datadrive/Crontab/google_budget.sh: Permission denied
/datadrive/Crontab/google_automation.py:531: DeprecationWarning:

The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

After 1000 initial trials Ad C got the highest CTR = 0.22 (Real CTR value is 0.25 ).
It will be shown 85.0 % of the time.
EpsilonGreedy
C    0.859
A    0.049
B    0.047
D    0.045
dtype: float64
/datadrive/Crontab/google_automation.py:531: DeprecationWarning:

The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

After 1000 initial trials Ad C got the highest CTR = 0.25 (Real CTR value is 0.25 ).
It will be shown 85.0 % of the time.
ThompsonSampling
C    0.8825
D    0.0605
A    0.0290
B    0.0280
dtype: float64
/datadrive/Crontab/google_automation.py:531: DeprecationWarning:

The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

After 1000 initial trials Ad C got the highest CTR = 0.44 (Real CTR value is 0.43 ).
It will be shown 85.0 % of the time.
EpsilonGreedy
Ucb1
C    0.5640
D    0.3760
B    0.0305
A    0.0295
dtype: float64
/datadrive/Crontab/google_automation.py:531: DeprecationWarning:

The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

After 1000 initial trials Ad C got the highest CTR = 0.33 (Real CTR value is 0.33 ).
It will be shown 85.0 % of the time.
ThompsonSampling
C    0.7205
D    0.2160
A    0.0320
B    0.0315
dtype: float64
2021-05-27 00:00:01
/datadrive/Crontab/google_automation.py:531: DeprecationWarning:

The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

After 1000 initial trials Ad C got the highest CTR = 0.42 (Real CTR value is 0.38 ).
It will be shown 85.0 % of the time.
Ucb1
C    0.8660
D    0.0700
B    0.0335
A    0.0305
dtype: float64
2021-05-28 00:00:01
/datadrive/Crontab/google_automation.py:531: DeprecationWarning:

The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

After 1000 initial trials Ad C got the highest CTR = 0.3 (Real CTR value is 0.32 ).
It will be shown 85.0 % of the time.
ThompsonSampling
C    0.8770
D    0.0585
A    0.0345
B    0.0300
dtype: float64
2021-05-29 00:00:01
/datadrive/Crontab/google_automation.py:531: DeprecationWarning:

The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

After 1000 initial trials Ad C got the highest CTR = 0.36 (Real CTR value is 0.34 ).
It will be shown 85.0 % of the time.
ThompsonSampling
C    0.8045
D    0.1380
B    0.0290
A    0.0285
dtype: float64
2021-05-30 00:00:01
/datadrive/Crontab/google_automation.py:55: RuntimeWarning: invalid value encountered in long_scalars
  ctr = round((clicks / impressions) * 100, ndigits=2)
Traceback (most recent call last):
  File "/datadrive/Crontab/google_automation.py", line 194, in <module>
    did_click = bernoulli.rvs(ACTUAL_CTR[random_ad]) # simulate if the person clicked on the ad usind Actual CTR value
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2997, in rvs
    return super(rv_discrete, self).rvs(*args, **kwargs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 979, in rvs
    raise ValueError("Domain error in arguments.")
ValueError: Domain error in arguments.
2021-05-31 00:00:01
/datadrive/Crontab/google_automation.py:55: RuntimeWarning: invalid value encountered in long_scalars
  ctr = round((clicks / impressions) * 100, ndigits=2)
Traceback (most recent call last):
  File "/datadrive/Crontab/google_automation.py", line 194, in <module>
    did_click = bernoulli.rvs(ACTUAL_CTR[random_ad]) # simulate if the person clicked on the ad usind Actual CTR value
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2997, in rvs
    return super(rv_discrete, self).rvs(*args, **kwargs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 979, in rvs
    raise ValueError("Domain error in arguments.")
ValueError: Domain error in arguments.
2021-06-01 00:00:01
/datadrive/Crontab/google_automation.py:55: RuntimeWarning: invalid value encountered in long_scalars
  ctr = round((clicks / impressions) * 100, ndigits=2)
Traceback (most recent call last):
  File "/datadrive/Crontab/google_automation.py", line 194, in <module>
    did_click = bernoulli.rvs(ACTUAL_CTR[random_ad]) # simulate if the person clicked on the ad usind Actual CTR value
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2997, in rvs
    return super(rv_discrete, self).rvs(*args, **kwargs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 979, in rvs
    raise ValueError("Domain error in arguments.")
ValueError: Domain error in arguments.
2021-06-02 00:00:01
/datadrive/Crontab/google_automation.py:55: RuntimeWarning: invalid value encountered in long_scalars
  ctr = round((clicks / impressions) * 100, ndigits=2)
Traceback (most recent call last):
  File "/datadrive/Crontab/google_automation.py", line 194, in <module>
    did_click = bernoulli.rvs(ACTUAL_CTR[random_ad]) # simulate if the person clicked on the ad usind Actual CTR value
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2997, in rvs
    return super(rv_discrete, self).rvs(*args, **kwargs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 979, in rvs
    raise ValueError("Domain error in arguments.")
ValueError: Domain error in arguments.
2021-06-03 00:00:01
/datadrive/Crontab/google_automation.py:55: RuntimeWarning: invalid value encountered in long_scalars
  ctr = round((clicks / impressions) * 100, ndigits=2)
Traceback (most recent call last):
  File "/datadrive/Crontab/google_automation.py", line 194, in <module>
    did_click = bernoulli.rvs(ACTUAL_CTR[random_ad]) # simulate if the person clicked on the ad usind Actual CTR value
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2997, in rvs
    return super(rv_discrete, self).rvs(*args, **kwargs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 979, in rvs
    raise ValueError("Domain error in arguments.")
ValueError: Domain error in arguments.
2021-06-04 00:00:01
/datadrive/Crontab/google_automation.py:55: RuntimeWarning: invalid value encountered in long_scalars
  ctr = round((clicks / impressions) * 100, ndigits=2)
Traceback (most recent call last):
  File "/datadrive/Crontab/google_automation.py", line 194, in <module>
    did_click = bernoulli.rvs(ACTUAL_CTR[random_ad]) # simulate if the person clicked on the ad usind Actual CTR value
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2997, in rvs
    return super(rv_discrete, self).rvs(*args, **kwargs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 979, in rvs
    raise ValueError("Domain error in arguments.")
ValueError: Domain error in arguments.
2021-06-05 00:00:01
/datadrive/Crontab/google_automation.py:55: RuntimeWarning: invalid value encountered in long_scalars
  ctr = round((clicks / impressions) * 100, ndigits=2)
Traceback (most recent call last):
  File "/datadrive/Crontab/google_automation.py", line 194, in <module>
    did_click = bernoulli.rvs(ACTUAL_CTR[random_ad]) # simulate if the person clicked on the ad usind Actual CTR value
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2997, in rvs
    return super(rv_discrete, self).rvs(*args, **kwargs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 979, in rvs
    raise ValueError("Domain error in arguments.")
ValueError: Domain error in arguments.
2021-06-06 00:00:01
/datadrive/Crontab/google_automation.py:55: RuntimeWarning: invalid value encountered in long_scalars
  ctr = round((clicks / impressions) * 100, ndigits=2)
Traceback (most recent call last):
  File "/datadrive/Crontab/google_automation.py", line 194, in <module>
    did_click = bernoulli.rvs(ACTUAL_CTR[random_ad]) # simulate if the person clicked on the ad usind Actual CTR value
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2997, in rvs
    return super(rv_discrete, self).rvs(*args, **kwargs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 979, in rvs
    raise ValueError("Domain error in arguments.")
ValueError: Domain error in arguments.
2021-06-07 00:00:01
/datadrive/Crontab/google_automation.py:55: RuntimeWarning: invalid value encountered in long_scalars
  ctr = round((clicks / impressions) * 100, ndigits=2)
Traceback (most recent call last):
  File "/datadrive/Crontab/google_automation.py", line 194, in <module>
    did_click = bernoulli.rvs(ACTUAL_CTR[random_ad]) # simulate if the person clicked on the ad usind Actual CTR value
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2997, in rvs
    return super(rv_discrete, self).rvs(*args, **kwargs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 979, in rvs
    raise ValueError("Domain error in arguments.")
ValueError: Domain error in arguments.
